
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xa5\x8f\x0ch\xea\n\x89\xcfUs\xc6\xd1\xcfnn\xeb'
    
_lr_action_items = {'MINUS':([14,15,17,22,23,24,25,26,],[-13,20,20,-12,20,20,20,20,]),'MULT':([14,15,17,22,23,24,25,26,],[-13,18,18,-12,18,18,18,18,]),'$end':([1,2,3,5,7,8,9,11,14,15,16,22,23,24,25,26,],[-1,-3,-2,-5,0,-7,-15,-6,-13,-4,-14,-12,-9,-11,-10,-8,]),'ID':([0,4,6,10,12,13,18,19,20,21,],[5,9,9,14,9,14,14,14,14,14,]),'WHILE':([0,],[6,]),'IF':([0,],[4,]),'RELOP':([8,9,11,16,],[12,-15,12,12,]),'DIV':([14,15,17,22,23,24,25,26,],[-13,19,19,-12,19,19,19,19,]),'EQUALS':([5,],[10,]),'CLBR':([14,17,22,23,24,25,26,],[-13,22,-12,-9,-11,-10,-8,]),'PLUS':([14,15,17,22,23,24,25,26,],[-13,21,21,-12,21,21,21,21,]),'OPBR':([10,13,18,19,20,21,],[13,13,13,13,13,13,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence1':([0,],[1,]),'sentence3':([0,],[2,]),'sentence2':([0,],[3,]),'boo':([4,6,12,],[8,11,16,]),'initial':([0,],[7,]),'expression':([10,13,18,19,20,21,],[15,17,23,24,25,26,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> initial","S'",1,None,None,None),
  ('initial -> sentence1','initial',1,'p_initial','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',100),
  ('initial -> sentence2','initial',1,'p_initial','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',101),
  ('initial -> sentence3','initial',1,'p_initial','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',102),
  ('sentence1 -> ID EQUALS expression','sentence1',3,'p_sentence','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',106),
  ('sentence1 -> ID','sentence1',1,'p_sentence','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',107),
  ('sentence2 -> WHILE boo','sentence2',2,'p_while','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',137),
  ('sentence3 -> IF boo','sentence3',2,'p_if','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',147),
  ('expression -> expression PLUS expression','expression',3,'p_expression_add','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',157),
  ('expression -> expression MULT expression','expression',3,'p_expression_mult','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',162),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',166),
  ('expression -> expression DIV expression','expression',3,'p_expression_divide','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',170),
  ('expression -> OPBR expression CLBR','expression',3,'p_expression_brackets','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',174),
  ('expression -> ID','expression',1,'p_expression','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',179),
  ('boo -> boo RELOP boo','boo',3,'p_relop','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',184),
  ('boo -> ID','boo',1,'p_relop','E:\\sanju\\5th Sem\\CD\\project final\\asdf\\sdt_final_2.py',185),
]
